/**
 * Email Theme Colors (Auto-generated)
 *
 * DO NOT EDIT MANUALLY - This file is generated by:
 *   npx tsx scripts/sync-email-theme.ts
 *
 * Generated: 2025-11-28T22:57:29.303Z
 * Source: src/app/globals.css
 *
 * Converts oklch theme colors to hex for email compatibility.
 * Emails don't support oklch, so we need hex values.
 */

export const emailThemeColors = {
  // Primary brand color (buttons, accents, highlights)
  primary: '#9B2C2C',
  primaryForeground: '#FFFFFF',

  // Secondary colors
  secondary: '#FDF2D6',
  secondaryForeground: '#805500',

  // Accent colors
  accent: '#FEF3C7',
  accentForeground: '#7F1D1D',

  // Neutral colors
  background: '#FAF7F5',
  foreground: '#1A1A1A',

  // Muted colors (secondary text, borders)
  muted: '#F0EBE8',
  mutedForeground: '#57534E',

  // Border color
  border: '#F5E8D2',

  // Card colors
  card: '#FAF7F5',
  cardForeground: '#1A1A1A',

  // Destructive (errors)
  destructive: '#991B1B',
  destructiveForeground: '#FFFFFF',

  // Semantic colors (fixed - not theme dependent)
  success: '#059669',
  successBackground: '#ECFDF5',
  successForeground: '#065F46',

  error: '#DC2626',
  errorBackground: '#FEF2F2',
  errorForeground: '#7F1D1D',

  warning: '#D97706',
  warningBackground: '#FFFBEB',
  warningForeground: '#92400E',
}

/**
 * Get color with fallback
 */
export function getEmailColor(
  colorName: keyof typeof emailThemeColors,
  fallback?: string
): string {
  return emailThemeColors[colorName] || fallback || '#000000'
}
