/**
 * Sync Email Theme Colors
 *
 * Automatically reads oklch colors from globals.css and converts them
 * to hex values for email compatibility.
 *
 * Usage:
 *   npx tsx scripts/sync-email-theme.ts
 *
 * Run this after changing the theme in globals.css or importing a new
 * shadcn theme via tweakcn.
 */

import * as fs from 'fs'
import * as path from 'path'

const GLOBALS_CSS_PATH = path.join(__dirname, '..', 'src', 'app', 'globals.css')
const THEME_COLORS_PATH = path.join(__dirname, '..', 'src', 'emails', 'config', 'theme-colors.ts')

/**
 * Convert oklch to RGB
 * oklch(L C H) where:
 *   L = lightness (0-1)
 *   C = chroma (0-0.4+)
 *   H = hue (0-360)
 */
function oklchToRgb(l: number, c: number, h: number): [number, number, number] {
  // Convert hue to radians
  const hRad = (h * Math.PI) / 180

  // oklch to oklab
  const a = c * Math.cos(hRad)
  const b = c * Math.sin(hRad)

  // oklab to linear RGB via LMS
  const L_ = l + 0.3963377774 * a + 0.2158037573 * b
  const M_ = l - 0.1055613458 * a - 0.0638541728 * b
  const S_ = l - 0.0894841775 * a - 1.291485548 * b

  const L = L_ * L_ * L_
  const M = M_ * M_ * M_
  const S = S_ * S_ * S_

  // LMS to linear RGB
  let r = +4.0767416621 * L - 3.3077115913 * M + 0.2309699292 * S
  let g = -1.2684380046 * L + 2.6097574011 * M - 0.3413193965 * S
  let bl = -0.0041960863 * L - 0.7034186147 * M + 1.707614701 * S

  // Linear RGB to sRGB (gamma correction)
  const toSrgb = (x: number) => {
    if (x <= 0) return 0
    if (x >= 1) return 1
    return x <= 0.0031308 ? 12.92 * x : 1.055 * Math.pow(x, 1 / 2.4) - 0.055
  }

  r = Math.round(toSrgb(r) * 255)
  g = Math.round(toSrgb(g) * 255)
  bl = Math.round(toSrgb(bl) * 255)

  // Clamp values
  r = Math.max(0, Math.min(255, r))
  g = Math.max(0, Math.min(255, g))
  bl = Math.max(0, Math.min(255, bl))

  return [r, g, bl]
}

/**
 * Convert RGB to hex
 */
function rgbToHex(r: number, g: number, b: number): string {
  return '#' + [r, g, b].map(x => x.toString(16).padStart(2, '0')).join('').toUpperCase()
}

/**
 * Parse oklch string and convert to hex
 */
function oklchToHex(oklchStr: string): string {
  // Match oklch(L C H) or oklch(L C H / alpha)
  const match = oklchStr.match(/oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)/)
  if (!match) {
    console.warn(`Could not parse oklch: ${oklchStr}`)
    return '#000000'
  }

  const l = parseFloat(match[1])
  const c = parseFloat(match[2])
  const h = parseFloat(match[3])

  const [r, g, b] = oklchToRgb(l, c, h)
  return rgbToHex(r, g, b)
}

/**
 * Extract CSS variables from :root block
 */
function extractCssVariables(css: string): Map<string, string> {
  const variables = new Map<string, string>()

  // Find :root block (light theme)
  const rootMatch = css.match(/:root\s*\{([^}]+)\}/)
  if (!rootMatch) {
    console.error('Could not find :root block in CSS')
    return variables
  }

  const rootContent = rootMatch[1]

  // Extract each variable
  const varRegex = /--([a-zA-Z0-9-]+):\s*([^;]+);/g
  let match
  while ((match = varRegex.exec(rootContent)) !== null) {
    const name = match[1]
    const value = match[2].trim()
    variables.set(name, value)
  }

  return variables
}

/**
 * Generate the theme-colors.ts file content
 */
function generateThemeColorsFile(variables: Map<string, string>): string {
  const getHex = (varName: string, fallback: string = '#000000'): string => {
    const value = variables.get(varName)
    if (!value) return fallback
    if (value.startsWith('oklch')) {
      return oklchToHex(value)
    }
    return value
  }

  const colors = {
    primary: getHex('primary'),
    primaryForeground: getHex('primary-foreground', '#FFFFFF'),
    secondary: getHex('secondary'),
    secondaryForeground: getHex('secondary-foreground'),
    accent: getHex('accent'),
    accentForeground: getHex('accent-foreground'),
    background: getHex('background', '#FFFFFF'),
    foreground: getHex('foreground', '#000000'),
    muted: getHex('muted'),
    mutedForeground: getHex('muted-foreground'),
    border: getHex('border'),
    card: getHex('card'),
    cardForeground: getHex('card-foreground'),
    destructive: getHex('destructive'),
    destructiveForeground: getHex('destructive-foreground'),
  }

  const timestamp = new Date().toISOString()

  return `/**
 * Email Theme Colors (Auto-generated)
 *
 * DO NOT EDIT MANUALLY - This file is generated by:
 *   npx tsx scripts/sync-email-theme.ts
 *
 * Generated: ${timestamp}
 * Source: src/app/globals.css
 *
 * Converts oklch theme colors to hex for email compatibility.
 * Emails don't support oklch, so we need hex values.
 */

export const emailThemeColors = {
  // Primary brand color (buttons, accents, highlights)
  primary: '${colors.primary}',
  primaryForeground: '${colors.primaryForeground}',

  // Secondary colors
  secondary: '${colors.secondary}',
  secondaryForeground: '${colors.secondaryForeground}',

  // Accent colors
  accent: '${colors.accent}',
  accentForeground: '${colors.accentForeground}',

  // Neutral colors
  background: '${colors.background}',
  foreground: '${colors.foreground}',

  // Muted colors (secondary text, borders)
  muted: '${colors.muted}',
  mutedForeground: '${colors.mutedForeground}',

  // Border color
  border: '${colors.border}',

  // Card colors
  card: '${colors.card}',
  cardForeground: '${colors.cardForeground}',

  // Destructive (errors)
  destructive: '${colors.destructive}',
  destructiveForeground: '${colors.destructiveForeground}',

  // Semantic colors (fixed - not theme dependent)
  success: '#059669',
  successBackground: '#ECFDF5',
  successForeground: '#065F46',

  error: '#DC2626',
  errorBackground: '#FEF2F2',
  errorForeground: '#7F1D1D',

  warning: '#D97706',
  warningBackground: '#FFFBEB',
  warningForeground: '#92400E',
}

/**
 * Get color with fallback
 */
export function getEmailColor(
  colorName: keyof typeof emailThemeColors,
  fallback?: string
): string {
  return emailThemeColors[colorName] || fallback || '#000000'
}
`
}

async function main() {
  console.log('🎨 Syncing Email Theme Colors')
  console.log('==============================\n')

  // Read globals.css
  if (!fs.existsSync(GLOBALS_CSS_PATH)) {
    console.error(`❌ Could not find: ${GLOBALS_CSS_PATH}`)
    process.exit(1)
  }

  console.log(`📖 Reading: ${GLOBALS_CSS_PATH}`)
  const css = fs.readFileSync(GLOBALS_CSS_PATH, 'utf-8')

  // Extract variables
  console.log('🔍 Extracting CSS variables...')
  const variables = extractCssVariables(css)
  console.log(`   Found ${variables.size} variables`)

  // Show key colors being converted
  const keyVars = ['primary', 'background', 'foreground', 'muted', 'border']
  console.log('\n📊 Key color conversions:')
  for (const varName of keyVars) {
    const oklch = variables.get(varName)
    if (oklch) {
      const hex = oklch.startsWith('oklch') ? oklchToHex(oklch) : oklch
      console.log(`   --${varName}: ${oklch.substring(0, 30)}... → ${hex}`)
    }
  }

  // Generate file
  console.log('\n📝 Generating theme-colors.ts...')
  const content = generateThemeColorsFile(variables)

  // Write file
  fs.writeFileSync(THEME_COLORS_PATH, content)
  console.log(`✅ Saved: ${THEME_COLORS_PATH}`)

  console.log('\n✨ Theme sync complete!')
  console.log('   Email templates will now use the updated colors.')
  console.log('\n💡 Tip: Run this script after changing your shadcn theme.')
}

main().catch(console.error)
